//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;html lang=&quot;en&quot;&gt;&lt;head&gt;
        ///    &lt;title&gt;The Pirate Bay - The galaxy&apos;s most resilient bittorrent site&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;google-site-verification&quot; content=&quot;bERYeomIC5eBWlPLupPPYPYGA9GvAUKzFHh3WIw24Xs&quot;&gt;
        ///    &lt;link rel=&quot;search&quot; type=&quot;application/opensearchdescription+xml&quot; href=&quot;/opensearch.xml&quot; title=&quot;Search The Pirate Bay&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;//pirateproxy.red/static/css/pirate6.css&quot;&gt;
        ///    &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PiratePageDifferentShowName {
            get {
                return ResourceManager.GetString("PiratePageDifferentShowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;&lt;head&gt;
        ///    &lt;title&gt;The Pirate Bay - The galaxy&apos;s most resilient bittorrent site&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;google-site-verification&quot; content=&quot;bERYeomIC5eBWlPLupPPYPYGA9GvAUKzFHh3WIw24Xs&quot;&gt;
        ///    &lt;link rel=&quot;search&quot; type=&quot;application/opensearchdescription+xml&quot; href=&quot;/opensearch.xml&quot; title=&quot;Search The Pirate Bay&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;//pirateproxy.red/static/css/pirate6.css&quot;&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PiratePageHDOnly {
            get {
                return ResourceManager.GetString("PiratePageHDOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;&lt;head&gt;
        ///    &lt;title&gt;The Pirate Bay - The galaxy&apos;s most resilient bittorrent site&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;google-site-verification&quot; content=&quot;bERYeomIC5eBWlPLupPPYPYGA9GvAUKzFHh3WIw24Xs&quot;&gt;
        ///    &lt;link rel=&quot;search&quot; type=&quot;application/opensearchdescription+xml&quot; href=&quot;/opensearch.xml&quot; title=&quot;Search The Pirate Bay&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;//pirateproxy.red/static/css/pirate6.css&quot;&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PiratePageNoResults {
            get {
                return ResourceManager.GetString("PiratePageNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;html lang=&quot;en&quot;&gt;&lt;head&gt;
        ///    &lt;title&gt;The Pirate Bay - The galaxy&apos;s most resilient bittorrent site&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;google-site-verification&quot; content=&quot;bERYeomIC5eBWlPLupPPYPYGA9GvAUKzFHh3WIw24Xs&quot;&gt;
        ///    &lt;link rel=&quot;search&quot; type=&quot;application/opensearchdescription+xml&quot; href=&quot;/opensearch.xml&quot; title=&quot;Search The Pirate Bay&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;//pirateproxy.red/static/css/pirate6.css&quot;&gt;
        ///    &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PiratePageSDOnly {
            get {
                return ResourceManager.GetString("PiratePageSDOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;&lt;head&gt;
        ///    &lt;title&gt;The Pirate Bay - The galaxy&apos;s most resilient bittorrent site&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;google-site-verification&quot; content=&quot;bERYeomIC5eBWlPLupPPYPYGA9GvAUKzFHh3WIw24Xs&quot;&gt;
        ///    &lt;link rel=&quot;search&quot; type=&quot;application/opensearchdescription+xml&quot; href=&quot;/opensearch.xml&quot; title=&quot;Search The Pirate Bay&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;//pirateproxy.red/static/css/pirate6.css&quot;&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PiratePageSearch {
            get {
                return ResourceManager.GetString("PiratePageSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;&lt;head&gt;
        ///    &lt;title&gt;The Pirate Bay - The galaxy&apos;s most resilient bittorrent site&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;google-site-verification&quot; content=&quot;bERYeomIC5eBWlPLupPPYPYGA9GvAUKzFHh3WIw24Xs&quot;&gt;
        ///    &lt;link rel=&quot;search&quot; type=&quot;application/opensearchdescription+xml&quot; href=&quot;/opensearch.xml&quot; title=&quot;Search The Pirate Bay&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;//pirateproxy.red/static/css/pirate6.css&quot;&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PiratePageSearch5Rows {
            get {
                return ResourceManager.GetString("PiratePageSearch5Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr class=&quot;header&quot;&gt;
        ///			&lt;th&gt;&lt;a href=&quot;/search/Rick%20And%20Morty/0/13/205,208&quot; title=&quot;Order by Type&quot;&gt;Type&lt;/a&gt;&lt;/th&gt;
        ///			&lt;th&gt;&lt;div class=&quot;sortby&quot;&gt;&lt;a href=&quot;/search/Rick%20And%20Morty/0/1/205,208&quot; title=&quot;Order by Name&quot;&gt;Name&lt;/a&gt; (Order by: &lt;a href=&quot;/search/Rick%20And%20Morty/0/3/205,208&quot; title=&quot;Order by Uploaded&quot;&gt;Uploaded&lt;/a&gt;, &lt;a href=&quot;/search/Rick%20And%20Morty/0/5/205,208&quot; title=&quot;Order by Size&quot;&gt;Size&lt;/a&gt;, &lt;span style=&quot;white-space: nowrap;&quot;&gt;&lt;a href=&quot;/search/Rick%20And%20Morty/0/11/205,208&quot; title=&quot;Order by ULed by&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PiratePageSearch5RowsSplit {
            get {
                return ResourceManager.GetString("PiratePageSearch5RowsSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;tr class=&quot;header&quot;&gt;
        ///			&lt;th&gt;&lt;a href=&quot;/search/Rick%20And%20Morty/0/13/205,208&quot; title=&quot;Order by Type&quot;&gt;Type&lt;/a&gt;&lt;/th&gt;
        ///			&lt;th&gt;&lt;div class=&quot;sortby&quot;&gt;&lt;a href=&quot;/search/Rick%20And%20Morty/0/1/205,208&quot; title=&quot;Order by Name&quot;&gt;Name&lt;/a&gt; (Order by: &lt;a href=&quot;/search/Rick%20And%20Morty/0/3/205,208&quot; title=&quot;Order by Uploaded&quot;&gt;Uploaded&lt;/a&gt;, &lt;a href=&quot;/search/Rick%20And%20Morty/0/5/205,208&quot; title=&quot;Order by Size&quot;&gt;Size&lt;/a&gt;, &lt;span style=&quot;white-space: nowrap;&quot;&gt;&lt;a href=&quot;/search/Rick%20And%20Morty/0/11/205,208&quot; title=&quot;Order by ULed b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PiratePageSearchSplit {
            get {
                return ResourceManager.GetString("PiratePageSearchSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;html lang=&quot;en&quot;&gt;&lt;head&gt;
        ///    &lt;title&gt;The Pirate Bay - The galaxy&apos;s most resilient bittorrent site&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;google-site-verification&quot; content=&quot;bERYeomIC5eBWlPLupPPYPYGA9GvAUKzFHh3WIw24Xs&quot;&gt;
        ///    &lt;link rel=&quot;search&quot; type=&quot;application/opensearchdescription+xml&quot; href=&quot;/opensearch.xml&quot; title=&quot;Search The Pirate Bay&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;//pirateproxy.red/static/css/pirate6.css&quot;&gt;
        ///    &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PiratePageSingleEpisode {
            get {
                return ResourceManager.GetString("PiratePageSingleEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;html lang=&quot;en&quot;&gt;&lt;head&gt;
        ///    &lt;title&gt;The Pirate Bay - The galaxy&apos;s most resilient bittorrent site&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;google-site-verification&quot; content=&quot;bERYeomIC5eBWlPLupPPYPYGA9GvAUKzFHh3WIw24Xs&quot;&gt;
        ///    &lt;link rel=&quot;search&quot; type=&quot;application/opensearchdescription+xml&quot; href=&quot;/opensearch.xml&quot; title=&quot;Search The Pirate Bay&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;//pirateproxy.red/static/css/pirate6.css&quot;&gt;
        ///    &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PiratePageSingleSeason {
            get {
                return ResourceManager.GetString("PiratePageSingleSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///		&lt;td class=&quot;vertTh&quot;&gt;
        ///			&lt;center&gt;
        ///				&lt;a href=&quot;/browse/100&quot; title=&quot;More from this category&quot;&gt;Audio&lt;/a&gt;&lt;br&gt;
        ///				(&lt;a href=&quot;/browse/101&quot; title=&quot;More from this category&quot;&gt;Music&lt;/a&gt;)
        ///			&lt;/center&gt;
        ///		&lt;/td&gt;
        ///		&lt;td&gt;
        ///&lt;div class=&quot;detName&quot;&gt;			&lt;a href=&quot;/torrent/6063457/Edie_Brickell___New_Bohemians_-_Stranger_Things_(2006)&quot; class=&quot;detLink&quot; title=&quot;Details for Edie Brickell &amp;amp; New Bohemians - Stranger Things (2006)&quot;&gt;Edie Brickell &amp;amp; New Bohemians - Stranger Things (2006)&lt;/a&gt;
        ///&lt;/div&gt;
        ///&lt;a href=&quot;magnet:?xt=ur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TorrentRow0Seeds0Leeches {
            get {
                return ResourceManager.GetString("TorrentRow0Seeds0Leeches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr class=&quot;alt&quot;&gt;
        ///		&lt;td class=&quot;vertTh&quot;&gt;
        ///			&lt;center&gt;
        ///				&lt;a href=&quot;/browse/200&quot; title=&quot;More from this category&quot;&gt;Video&lt;/a&gt;&lt;br&gt;
        ///				(&lt;a href=&quot;/browse/208&quot; title=&quot;More from this category&quot;&gt;HD - TV shows&lt;/a&gt;)
        ///			&lt;/center&gt;
        ///		&lt;/td&gt;
        ///		&lt;td&gt;
        ///&lt;div class=&quot;detName&quot;&gt;			&lt;a href=&quot;/torrent/12162845/Rick_and_Morty_Season_1_[1080p]_[HEVC]&quot; class=&quot;detLink&quot; title=&quot;Details for Rick and Morty Season 1 [1080p] [HEVC]&quot;&gt;Rick and Morty Season 1 [1080p] [HEVC]&lt;/a&gt;
        ///&lt;/div&gt;
        ///&lt;a href=&quot;magnet:?xt=urn:btih:08ad112d3469f45ed490ffed8253 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TorrentRowAnonymousUploader {
            get {
                return ResourceManager.GetString("TorrentRowAnonymousUploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///		&lt;td class=&quot;vertTh&quot;&gt;
        ///			&lt;center&gt;
        ///				&lt;a href=&quot;/browse/100&quot; title=&quot;More from this category&quot;&gt;Audio&lt;/a&gt;&lt;br&gt;
        ///				(&lt;a href=&quot;/browse/101&quot; title=&quot;More from this category&quot;&gt;Music&lt;/a&gt;)
        ///			&lt;/center&gt;
        ///		&lt;/td&gt;
        ///		&lt;td&gt;
        ///&lt;div class=&quot;detName&quot;&gt;			&lt;a href=&quot;/torrent/15599437/Stranger_Things_vol._1__amp__2_soundtrack&quot; class=&quot;detLink&quot; title=&quot;Details for Stranger Things vol. 1 &amp;amp; 2 soundtrack&quot;&gt;Stranger Things vol. 1 &amp;amp; 2 soundtrack&lt;/a&gt;
        ///&lt;/div&gt;
        ///&lt;a href=&quot;magnet:?xt=urn:btih:d2a7e42ca278f125e3c27b62ad3381e713d1f6a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TorrentRowNoUploaderStatus {
            get {
                return ResourceManager.GetString("TorrentRowNoUploaderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///		&lt;td class=&quot;vertTh&quot;&gt;
        ///			&lt;center&gt;
        ///				&lt;a href=&quot;/browse/200&quot; title=&quot;More from this category&quot;&gt;Video&lt;/a&gt;&lt;br&gt;
        ///				(&lt;a href=&quot;/browse/208&quot; title=&quot;More from this category&quot;&gt;HD - TV shows&lt;/a&gt;)
        ///			&lt;/center&gt;
        ///		&lt;/td&gt;
        ///		&lt;td&gt;
        ///&lt;div class=&quot;detName&quot;&gt;			&lt;a href=&quot;/torrent/15314146/Stranger.Things.S01E05.720p.WEBRip.x264-SKGTV[ettv]&quot; class=&quot;detLink&quot; title=&quot;Details for Stranger.Things.S01E05.720p.WEBRip.x264-SKGTV[ettv]&quot;&gt;Stranger.Things.S01E05.720p.WEBRip.x264-SKGTV[ettv]&lt;/a&gt;
        ///&lt;/div&gt;
        ///&lt;a href=&quot;magnet:?xt=urn:btih:c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TorrentRowTrustedUploader {
            get {
                return ResourceManager.GetString("TorrentRowTrustedUploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///  &lt;td class=&quot;vertTh&quot;&gt;
        ///    &lt;center&gt;
        ///	  &lt;a href=&quot;/browse/200&quot; title=&quot;More from this category&quot;&gt;Video&lt;/a&gt;
        ///	  &lt;br&gt;
        ///	  (&lt;a href=&quot;/browse/208&quot; title=&quot;More from this category&quot;&gt;HD - TV shows&lt;/a&gt;)
        ///	&lt;/center&gt;
        ///  &lt;/td&gt;
        ///  &lt;td&gt;
        ///    &lt;div class=&quot;detName&quot;&gt;
        ///      &lt;a href=&quot;/torrent/12678054/Rick_and_Morty_Season_2_[WEBRIP]_[1080p]_[HEVC]&quot; class=&quot;detLink&quot; title=&quot;Details for Rick and Morty Season 2 [WEBRIP] [1080p] [HEVC]&quot;&gt;
        ///	    Rick and Morty Season 2 [WEBRIP] [1080p] [HEVC]
        ///	  &lt;/a&gt;
        ///    &lt;/div&gt;
        ///    &lt;a href=&quot;ma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TorrentRowVipUploader {
            get {
                return ResourceManager.GetString("TorrentRowVipUploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///  &lt;td class=&quot;vertTh&quot;&gt;
        ///    &lt;center&gt;
        ///	  &lt;a href=&quot;/browse/200&quot; title=&quot;More from this category&quot;&gt;Video&lt;/a&gt;
        ///	  &lt;br&gt;
        ///	  (&lt;a href=&quot;/browse/208&quot; title=&quot;More from this category&quot;&gt;HD - TV shows&lt;/a&gt;)
        ///	&lt;/center&gt;
        ///  &lt;/td&gt;
        ///  &lt;td&gt;
        ///    &lt;div class=&quot;detName&quot;&gt;
        ///      &lt;a href=&quot;/torrent/12678054/Rick_and_Morty_Season_2_[WEBRIP]_[1080p]_[HEVC]&quot; class=&quot;detLink&quot; title=&quot;Details for Rick and Morty Season 2 [WEBRIP] [1080p] [HEVC]&quot;&gt;		      		Rick and Morty Season 2 [WEBRIP] [1080p] [HEVC]     	  &lt;/a&gt;
        ///    &lt;/div&gt;
        ///    &lt;a hr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TorrentRowWhiteSpaceAroundTitle {
            get {
                return ResourceManager.GetString("TorrentRowWhiteSpaceAroundTitle", resourceCulture);
            }
        }
    }
}
