//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PirateAPITests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PirateAPITests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;caps&gt;
        ///  &lt;server version=&quot;1.0&quot; title=&quot;PirateAPI&quot; strapline=&quot;A Torznab API for TPB&quot; url=&quot;https://github.com/Thosedarnmonkeys/PirateAPI&quot;/&gt;
        ///
        ///  &lt;limits max=&quot;50&quot; default=&quot;50&quot;/&gt;
        ///
        ///  &lt;registration available=&quot;no&quot; open=&quot;no&quot; /&gt;
        ///
        ///  &lt;searching&gt;
        ///      &lt;search available=&quot;yes&quot; supportedParams=&quot;q&quot; /&gt;
        ///      &lt;tv-search available=&quot;yes&quot; supportedParams=&quot;q,season,ep&quot; /&gt;
        ///  &lt;/searching&gt;
        ///
        ///  &lt;categories&gt;
        ///      &lt;category id=&quot;5000&quot; name=&quot;TV&quot;&gt;
        ///        &lt;subcat id=&quot;5030&quot; name=&quot;SDTV&quot;/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CapsResponseBasic {
            get {
                return ResourceManager.GetString("CapsResponseBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;caps&gt;
        ///  &lt;server version=&quot;1.0&quot; title=&quot;PirateAPI&quot; strapline=&quot;A Torznab API for TPB&quot; url=&quot;https://github.com/Thosedarnmonkeys/PirateAPI&quot;/&gt;
        ///
        ///  &lt;limits max=&quot;0&quot; default=&quot;0&quot;/&gt;
        ///
        ///  &lt;registration available=&quot;no&quot; open=&quot;no&quot; /&gt;
        ///
        ///  &lt;searching&gt;
        ///      &lt;search available=&quot;yes&quot; supportedParams=&quot;q&quot; /&gt;
        ///      &lt;tv-search available=&quot;yes&quot; supportedParams=&quot;q,season,ep&quot; /&gt;
        ///  &lt;/searching&gt;
        ///
        ///  &lt;categories&gt;
        ///      &lt;category id=&quot;5000&quot; name=&quot;TV&quot;&gt;
        ///        &lt;subcat id=&quot;5030&quot; name=&quot;SDTV&quot;/&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CapsResponseLimit0 {
            get {
                return ResourceManager.GetString("CapsResponseLimit0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;caps&gt;
        ///  &lt;server version=&quot;1.0&quot; title=&quot;PirateAPI&quot; strapline=&quot;A Torznab API for TPB&quot; url=&quot;https://github.com/Thosedarnmonkeys/PirateAPI&quot;/&gt;
        ///
        ///  &lt;limits max=&quot;1&quot; default=&quot;1&quot;/&gt;
        ///
        ///  &lt;registration available=&quot;no&quot; open=&quot;no&quot; /&gt;
        ///
        ///  &lt;searching&gt;
        ///      &lt;search available=&quot;yes&quot; supportedParams=&quot;q&quot; /&gt;
        ///      &lt;tv-search available=&quot;yes&quot; supportedParams=&quot;q,season,ep&quot; /&gt;
        ///  &lt;/searching&gt;
        ///
        ///  &lt;categories&gt;
        ///      &lt;category id=&quot;5000&quot; name=&quot;TV&quot;&gt;
        ///        &lt;subcat id=&quot;5030&quot; name=&quot;SDTV&quot;/&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CapsResponseLimit1 {
            get {
                return ResourceManager.GetString("CapsResponseLimit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;caps&gt;
        ///  &lt;server version=&quot;1.0&quot; title=&quot;PirateAPI&quot; strapline=&quot;A Torznab API for TPB&quot; url=&quot;https://github.com/Thosedarnmonkeys/PirateAPI&quot;/&gt;
        ///
        ///  &lt;limits max=&quot;9&quot; default=&quot;9&quot;/&gt;
        ///
        ///  &lt;registration available=&quot;no&quot; open=&quot;no&quot; /&gt;
        ///
        ///  &lt;searching&gt;
        ///      &lt;search available=&quot;yes&quot; supportedParams=&quot;q&quot; /&gt;
        ///      &lt;tv-search available=&quot;yes&quot; supportedParams=&quot;q,season,ep&quot; /&gt;
        ///  &lt;/searching&gt;
        ///
        ///  &lt;categories&gt;
        ///      &lt;category id=&quot;5000&quot; name=&quot;TV&quot;&gt;
        ///        &lt;subcat id=&quot;5030&quot; name=&quot;SDTV&quot;/&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CapsResponseLimit9 {
            get {
                return ResourceManager.GetString("CapsResponseLimit9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr class=&quot;header&quot;&gt;
        ///			&lt;th&gt;Type&lt;/th&gt;
        ///			&lt;th&gt;&lt;div class=&quot;sortby&quot;&gt;Name&lt;/div&gt;&lt;div class=&quot;viewswitch&quot;&gt; View: &lt;a href=&quot;/switchview.php?view=s&quot;&gt;Single&lt;/a&gt; / Double&amp;nbsp;&lt;/div&gt;&lt;/th&gt;
        ///			&lt;th&gt;&lt;abbr title=&quot;Seeders&quot;&gt;SE&lt;/abbr&gt;&lt;/th&gt;
        ///			&lt;th&gt;&lt;abbr title=&quot;Leechers&quot;&gt;LE&lt;/abbr&gt;&lt;/th&gt;
        ///		&lt;/tr&gt;.
        /// </summary>
        internal static string NonTorrentRow {
            get {
                return ResourceManager.GetString("NonTorrentRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;html lang=&quot;en&quot;&gt;&lt;head&gt;
        ///    &lt;title&gt;The Pirate Bay - The galaxy&apos;s most resilient bittorrent site&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;google-site-verification&quot; content=&quot;bERYeomIC5eBWlPLupPPYPYGA9GvAUKzFHh3WIw24Xs&quot;&gt;
        ///    &lt;link rel=&quot;search&quot; type=&quot;application/opensearchdescription+xml&quot; href=&quot;/opensearch.xml&quot; title=&quot;Search The Pirate Bay&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;//pirateproxy.red/static/css/pirate6.css&quot;&gt;
        ///    &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PiratePageDifferentShowName {
            get {
                return ResourceManager.GetString("PiratePageDifferentShowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;&lt;head&gt;
        ///    &lt;title&gt;The Pirate Bay - The galaxy&apos;s most resilient bittorrent site&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;google-site-verification&quot; content=&quot;bERYeomIC5eBWlPLupPPYPYGA9GvAUKzFHh3WIw24Xs&quot;&gt;
        ///    &lt;link rel=&quot;search&quot; type=&quot;application/opensearchdescription+xml&quot; href=&quot;/opensearch.xml&quot; title=&quot;Search The Pirate Bay&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;//pirateproxy.red/static/css/pirate6.css&quot;&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PiratePageHDOnly {
            get {
                return ResourceManager.GetString("PiratePageHDOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;&lt;head&gt;
        ///    &lt;title&gt;The Pirate Bay - The galaxy&apos;s most resilient bittorrent site&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;google-site-verification&quot; content=&quot;bERYeomIC5eBWlPLupPPYPYGA9GvAUKzFHh3WIw24Xs&quot;&gt;
        ///    &lt;link rel=&quot;search&quot; type=&quot;application/opensearchdescription+xml&quot; href=&quot;/opensearch.xml&quot; title=&quot;Search The Pirate Bay&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;//pirateproxy.red/static/css/pirate6.css&quot;&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PiratePageNoResults {
            get {
                return ResourceManager.GetString("PiratePageNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;html lang=&quot;en&quot;&gt;&lt;head&gt;
        ///    &lt;title&gt;The Pirate Bay - The galaxy&apos;s most resilient bittorrent site&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;google-site-verification&quot; content=&quot;bERYeomIC5eBWlPLupPPYPYGA9GvAUKzFHh3WIw24Xs&quot;&gt;
        ///    &lt;link rel=&quot;search&quot; type=&quot;application/opensearchdescription+xml&quot; href=&quot;/opensearch.xml&quot; title=&quot;Search The Pirate Bay&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;//pirateproxy.red/static/css/pirate6.css&quot;&gt;
        ///    &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PiratePageSDOnly {
            get {
                return ResourceManager.GetString("PiratePageSDOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;&lt;head&gt;
        ///    &lt;title&gt;The Pirate Bay - The galaxy&apos;s most resilient bittorrent site&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;google-site-verification&quot; content=&quot;bERYeomIC5eBWlPLupPPYPYGA9GvAUKzFHh3WIw24Xs&quot;&gt;
        ///    &lt;link rel=&quot;search&quot; type=&quot;application/opensearchdescription+xml&quot; href=&quot;/opensearch.xml&quot; title=&quot;Search The Pirate Bay&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;//pirateproxy.red/static/css/pirate6.css&quot;&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PiratePageSearch {
            get {
                return ResourceManager.GetString("PiratePageSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;&lt;head&gt;
        ///    &lt;title&gt;The Pirate Bay - The galaxy&apos;s most resilient bittorrent site&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;google-site-verification&quot; content=&quot;bERYeomIC5eBWlPLupPPYPYGA9GvAUKzFHh3WIw24Xs&quot;&gt;
        ///    &lt;link rel=&quot;search&quot; type=&quot;application/opensearchdescription+xml&quot; href=&quot;/opensearch.xml&quot; title=&quot;Search The Pirate Bay&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;//pirateproxy.red/static/css/pirate6.css&quot;&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PiratePageSearch3RowsNoMagnets {
            get {
                return ResourceManager.GetString("PiratePageSearch3RowsNoMagnets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;&lt;head&gt;
        ///    &lt;title&gt;The Pirate Bay - The galaxy&apos;s most resilient bittorrent site&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;google-site-verification&quot; content=&quot;bERYeomIC5eBWlPLupPPYPYGA9GvAUKzFHh3WIw24Xs&quot;&gt;
        ///    &lt;link rel=&quot;search&quot; type=&quot;application/opensearchdescription+xml&quot; href=&quot;/opensearch.xml&quot; title=&quot;Search The Pirate Bay&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;//pirateproxy.red/static/css/pirate6.css&quot;&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PiratePageSearch5Rows {
            get {
                return ResourceManager.GetString("PiratePageSearch5Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr class=&quot;header&quot;&gt;
        ///			&lt;th&gt;&lt;a href=&quot;/search/Rick%20And%20Morty/0/13/205,208&quot; title=&quot;Order by Type&quot;&gt;Type&lt;/a&gt;&lt;/th&gt;
        ///			&lt;th&gt;&lt;div class=&quot;sortby&quot;&gt;&lt;a href=&quot;/search/Rick%20And%20Morty/0/1/205,208&quot; title=&quot;Order by Name&quot;&gt;Name&lt;/a&gt; (Order by: &lt;a href=&quot;/search/Rick%20And%20Morty/0/3/205,208&quot; title=&quot;Order by Uploaded&quot;&gt;Uploaded&lt;/a&gt;, &lt;a href=&quot;/search/Rick%20And%20Morty/0/5/205,208&quot; title=&quot;Order by Size&quot;&gt;Size&lt;/a&gt;, &lt;span style=&quot;white-space: nowrap;&quot;&gt;&lt;a href=&quot;/search/Rick%20And%20Morty/0/11/205,208&quot; title=&quot;Order by ULed by&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PiratePageSearch5RowsSplit {
            get {
                return ResourceManager.GetString("PiratePageSearch5RowsSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;tr class=&quot;header&quot;&gt;
        ///			&lt;th&gt;&lt;a href=&quot;/search/Rick%20And%20Morty/0/13/205,208&quot; title=&quot;Order by Type&quot;&gt;Type&lt;/a&gt;&lt;/th&gt;
        ///			&lt;th&gt;&lt;div class=&quot;sortby&quot;&gt;&lt;a href=&quot;/search/Rick%20And%20Morty/0/1/205,208&quot; title=&quot;Order by Name&quot;&gt;Name&lt;/a&gt; (Order by: &lt;a href=&quot;/search/Rick%20And%20Morty/0/3/205,208&quot; title=&quot;Order by Uploaded&quot;&gt;Uploaded&lt;/a&gt;, &lt;a href=&quot;/search/Rick%20And%20Morty/0/5/205,208&quot; title=&quot;Order by Size&quot;&gt;Size&lt;/a&gt;, &lt;span style=&quot;white-space: nowrap;&quot;&gt;&lt;a href=&quot;/search/Rick%20And%20Morty/0/11/205,208&quot; title=&quot;Order by ULed b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PiratePageSearchSplit {
            get {
                return ResourceManager.GetString("PiratePageSearchSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;html lang=&quot;en&quot;&gt;&lt;head&gt;
        ///    &lt;title&gt;The Pirate Bay - The galaxy&apos;s most resilient bittorrent site&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;google-site-verification&quot; content=&quot;bERYeomIC5eBWlPLupPPYPYGA9GvAUKzFHh3WIw24Xs&quot;&gt;
        ///    &lt;link rel=&quot;search&quot; type=&quot;application/opensearchdescription+xml&quot; href=&quot;/opensearch.xml&quot; title=&quot;Search The Pirate Bay&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;//pirateproxy.red/static/css/pirate6.css&quot;&gt;
        ///    &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PiratePageSingleEpisode {
            get {
                return ResourceManager.GetString("PiratePageSingleEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;html lang=&quot;en&quot;&gt;&lt;head&gt;
        ///    &lt;title&gt;The Pirate Bay - The galaxy&apos;s most resilient bittorrent site&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;google-site-verification&quot; content=&quot;bERYeomIC5eBWlPLupPPYPYGA9GvAUKzFHh3WIw24Xs&quot;&gt;
        ///    &lt;link rel=&quot;search&quot; type=&quot;application/opensearchdescription+xml&quot; href=&quot;/opensearch.xml&quot; title=&quot;Search The Pirate Bay&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;//pirateproxy.red/static/css/pirate6.css&quot;&gt;
        ///    &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PiratePageSingleSeason {
            get {
                return ResourceManager.GetString("PiratePageSingleSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;&lt;head&gt;&lt;title&gt;The Pirate Bay - The galaxy&apos;s most resilient bittorrent site&lt;/title&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;&lt;link rel=&quot;search&quot; type=&quot;application/opensearchdescription+xml&quot; href=&quot;/opensearch.xml&quot; title=&quot;Search The Pirate Bay&quot;&gt;&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;/static/css/pirate6.css&quot;&gt;&lt;link rel=&quot;canonical&quot; href=&quot;/top/200&quot;&gt;&lt;style type=&quot;text/css&quot;&gt;
        ///        .searchBox{
        ///            margin: 6px;
        ///            width: 300px;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PiratePageTop100NoMagnets {
            get {
                return ResourceManager.GetString("PiratePageTop100NoMagnets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;&lt;head&gt;
        ///    &lt;title&gt;The Pirate Bay - The galaxy&apos;s most resilient bittorrent site&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;google-site-verification&quot; content=&quot;bERYeomIC5eBWlPLupPPYPYGA9GvAUKzFHh3WIw24Xs&quot;&gt;
        ///    &lt;link rel=&quot;search&quot; type=&quot;application/opensearchdescription+xml&quot; href=&quot;/opensearch.xml&quot; title=&quot;Search The Pirate Bay&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;https://pirateproxy.vip/static/css/pirate6.css&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PiratePageTop100WithMagnets {
            get {
                return ResourceManager.GetString("PiratePageTop100WithMagnets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;proxies&quot;:[{&quot;domain&quot;:&quot;gameofbay.org&quot;,&quot;speed&quot;:5.002,&quot;secure&quot;:true,&quot;country&quot;:&quot;UK&quot;,&quot;probed&quot;:true},{&quot;domain&quot;:&quot;unblockedbay.info&quot;,&quot;speed&quot;:0.061,&quot;secure&quot;:true,&quot;country&quot;:&quot;US&quot;,&quot;probed&quot;:true},{&quot;domain&quot;:&quot;tpbunblocked.org&quot;,&quot;speed&quot;:1.112,&quot;secure&quot;:true,&quot;country&quot;:&quot;UK&quot;,&quot;probed&quot;:true},{&quot;domain&quot;:&quot;thepiratebay.uk.net&quot;,&quot;speed&quot;:0.179,&quot;secure&quot;:true,&quot;country&quot;:&quot;IT&quot;,&quot;probed&quot;:true},{&quot;domain&quot;:&quot;piratebay.host&quot;,&quot;speed&quot;:0.208,&quot;secure&quot;:false,&quot;country&quot;:&quot;NO&quot;,&quot;probed&quot;:true},{&quot;domain&quot;:&quot;piratebay.click&quot;,&quot;speed&quot;:0.416,&quot;secure&quot;:true,&quot;country&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProxyListBestProxyNowSlow {
            get {
                return ResourceManager.GetString("ProxyListBestProxyNowSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;proxies&quot;:[{&quot;domain&quot;:&quot;gameofbay.org&quot;,&quot;speed&quot;:0.002,&quot;secure&quot;:true,&quot;country&quot;:&quot;UK&quot;,&quot;probed&quot;:true},{&quot;domain&quot;:&quot;unblockedbay.info&quot;,&quot;speed&quot;:0.061,&quot;secure&quot;:true,&quot;country&quot;:&quot;US&quot;,&quot;probed&quot;:true},{&quot;domain&quot;:&quot;tpbunblocked.org&quot;,&quot;speed&quot;:1.112,&quot;secure&quot;:true,&quot;country&quot;:&quot;UK&quot;,&quot;probed&quot;:true},{&quot;domain&quot;:&quot;thepiratebay.uk.net&quot;,&quot;speed&quot;:0.179,&quot;secure&quot;:true,&quot;country&quot;:&quot;IT&quot;,&quot;probed&quot;:true},{&quot;domain&quot;:&quot;piratebay.host&quot;,&quot;speed&quot;:0.208,&quot;secure&quot;:false,&quot;country&quot;:&quot;NO&quot;,&quot;probed&quot;:true},{&quot;domain&quot;:&quot;piratebay.click&quot;,&quot;speed&quot;:0.416,&quot;secure&quot;:true,&quot;country&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProxyListSimple {
            get {
                return ResourceManager.GetString("ProxyListSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;&lt;head&gt;&lt;title&gt;Rick and Morty Season 2 [WEBRIP] [1080p] [HEVC] (download torrent) - TPB&lt;/title&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;&lt;link rel=&quot;search&quot; type=&quot;application/opensearchdescription+xml&quot; href=&quot;/opensearch.xml&quot; title=&quot;Search The Pirate Bay&quot;&gt;&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;/static/css/pirate6.css&quot;&gt;&lt;link rel=&quot;canonical&quot; href=&quot;/torrent/12678054/Rick_and_Morty_Season_2_%5BWEBRIP%5D_%5B1080p%5D_%5BHEVC%5D&quot;&gt;&lt;style type=&quot;text/css&quot;&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RickAndMortySeason2 {
            get {
                return ResourceManager.GetString("RickAndMortySeason2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///		&lt;td class=&quot;vertTh&quot;&gt;
        ///			&lt;center&gt;
        ///				&lt;a href=&quot;/browse/100&quot; title=&quot;More from this category&quot;&gt;Audio&lt;/a&gt;&lt;br&gt;
        ///				(&lt;a href=&quot;/browse/101&quot; title=&quot;More from this category&quot;&gt;Music&lt;/a&gt;)
        ///			&lt;/center&gt;
        ///		&lt;/td&gt;
        ///		&lt;td&gt;
        ///&lt;div class=&quot;detName&quot;&gt;			&lt;a href=&quot;/torrent/6063457/Edie_Brickell___New_Bohemians_-_Stranger_Things_(2006)&quot; class=&quot;detLink&quot; title=&quot;Details for Edie Brickell &amp;amp; New Bohemians - Stranger Things (2006)&quot;&gt;Edie Brickell &amp;amp; New Bohemians - Stranger Things (2006)&lt;/a&gt;
        ///&lt;/div&gt;
        ///&lt;a href=&quot;magnet:?xt=ur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TorrentRow0Seeds0Leeches {
            get {
                return ResourceManager.GetString("TorrentRow0Seeds0Leeches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr class=&quot;alt&quot;&gt;
        ///		&lt;td class=&quot;vertTh&quot;&gt;
        ///			&lt;center&gt;
        ///				&lt;a href=&quot;/browse/200&quot; title=&quot;More from this category&quot;&gt;Video&lt;/a&gt;&lt;br&gt;
        ///				(&lt;a href=&quot;/browse/208&quot; title=&quot;More from this category&quot;&gt;HD - TV shows&lt;/a&gt;)
        ///			&lt;/center&gt;
        ///		&lt;/td&gt;
        ///		&lt;td&gt;
        ///&lt;div class=&quot;detName&quot;&gt;			&lt;a href=&quot;/torrent/12162845/Rick_and_Morty_Season_1_[1080p]_[HEVC]&quot; class=&quot;detLink&quot; title=&quot;Details for Rick and Morty Season 1 [1080p] [HEVC]&quot;&gt;Rick and Morty Season 1 [1080p] [HEVC]&lt;/a&gt;
        ///&lt;/div&gt;
        ///&lt;a href=&quot;magnet:?xt=urn:btih:08ad112d3469f45ed490ffed8253 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TorrentRowAnonymousUploader {
            get {
                return ResourceManager.GetString("TorrentRowAnonymousUploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///		&lt;td class=&quot;vertTh&quot;&gt;
        ///			&lt;center&gt;
        ///				&lt;a href=&quot;/browse/200&quot; title=&quot;More from this category&quot;&gt;Video&lt;/a&gt;&lt;br&gt;
        ///				(&lt;a href=&quot;/browse/201&quot; title=&quot;More from this category&quot;&gt;Movies&lt;/a&gt;)
        ///			&lt;/center&gt;
        ///		&lt;/td&gt;
        ///		&lt;td&gt;
        ///&lt;div class=&quot;detName&quot;&gt;			&lt;a href=&quot;/torrent/16223850/Mothers.and.Daughters.2016.BRRip.XviD.AC3-EVO&quot; class=&quot;detLink&quot; title=&quot;Details for Mothers.and.Daughters.2016.BRRip.XviD.AC3-EVO&quot;&gt;Mothers.and.Daughters.2016.BRRip.XviD.AC3-EVO&lt;/a&gt;
        ///&lt;/div&gt;
        ///&lt;a href=&quot;magnet:?xt=urn:btih:9a5ba6f454374e561445b793bd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TorrentRowMinutesAgoPublish {
            get {
                return ResourceManager.GetString("TorrentRowMinutesAgoPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;&lt;td class=&quot;vertTh&quot;&gt;
        ///			&lt;center&gt;
        ///				&lt;a href=&quot;/browse/200&quot; title=&quot;More from this category&quot;&gt;Video&lt;/a&gt;&lt;br&gt;
        ///				(&lt;a href=&quot;/browse/208&quot; title=&quot;More from this category&quot;&gt;HD - TV shows&lt;/a&gt;)
        ///			&lt;/center&gt;
        ///		&lt;/td&gt;
        ///		&lt;td&gt;
        ///&lt;div class=&quot;detName&quot;&gt;			&lt;a href=&quot;/torrent/12678054/Rick_and_Morty_Season_2_%5BWEBRIP%5D_%5B1080p%5D_%5BHEVC%5D&quot; class=&quot;detLink&quot; title=&quot;Details for Rick and Morty Season 2 [WEBRIP] [1080p] [HEVC]&quot;&gt;Rick and Morty Season 2 [WEBRIP] [1080p] [HEVC]&lt;/a&gt;
        ///&lt;/div&gt;
        ///&lt;a href=&quot;/torrent/12678054/Rick_an [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TorrentRowNoMagnetLink {
            get {
                return ResourceManager.GetString("TorrentRowNoMagnetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///		&lt;td class=&quot;vertTh&quot;&gt;
        ///			&lt;center&gt;
        ///				&lt;a href=&quot;/browse/100&quot; title=&quot;More from this category&quot;&gt;Audio&lt;/a&gt;&lt;br&gt;
        ///				(&lt;a href=&quot;/browse/101&quot; title=&quot;More from this category&quot;&gt;Music&lt;/a&gt;)
        ///			&lt;/center&gt;
        ///		&lt;/td&gt;
        ///		&lt;td&gt;
        ///&lt;div class=&quot;detName&quot;&gt;			&lt;a href=&quot;/torrent/15599437/Stranger_Things_vol._1__amp__2_soundtrack&quot; class=&quot;detLink&quot; title=&quot;Details for Stranger Things vol. 1 &amp;amp; 2 soundtrack&quot;&gt;Stranger Things vol. 1 &amp;amp; 2 soundtrack&lt;/a&gt;
        ///&lt;/div&gt;
        ///&lt;a href=&quot;magnet:?xt=urn:btih:d2a7e42ca278f125e3c27b62ad3381e713d1f6a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TorrentRowNoUploaderStatus {
            get {
                return ResourceManager.GetString("TorrentRowNoUploaderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///		&lt;td class=&quot;vertTh&quot;&gt;
        ///			&lt;center&gt;
        ///				&lt;a href=&quot;/browse/200&quot; title=&quot;More from this category&quot;&gt;Video&lt;/a&gt;&lt;br&gt;
        ///				(&lt;a href=&quot;/browse/205&quot; title=&quot;More from this category&quot;&gt;TV shows&lt;/a&gt;)
        ///			&lt;/center&gt;
        ///		&lt;/td&gt;
        ///		&lt;td&gt;
        ///&lt;div class=&quot;detName&quot;&gt;			&lt;a href=&quot;/torrent/16221650/BBC.World.News.2016.09.21.(Eng.Subs).SDTV.x264-[2Maverick]&quot; class=&quot;detLink&quot; title=&quot;Details for BBC.World.News.2016.09.21.(Eng.Subs).SDTV.x264-[2Maverick]&quot;&gt;BBC.World.News.2016.09.21.(Eng.Subs).SDTV.x264-[2Maverick]&lt;/a&gt;
        ///&lt;/div&gt;
        ///&lt;a href=&quot;magne [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TorrentRowTodayWordPublish {
            get {
                return ResourceManager.GetString("TorrentRowTodayWordPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///		&lt;td class=&quot;vertTh&quot;&gt;
        ///			&lt;center&gt;
        ///				&lt;a href=&quot;/browse/200&quot; title=&quot;More from this category&quot;&gt;Video&lt;/a&gt;&lt;br&gt;
        ///				(&lt;a href=&quot;/browse/208&quot; title=&quot;More from this category&quot;&gt;HD - TV shows&lt;/a&gt;)
        ///			&lt;/center&gt;
        ///		&lt;/td&gt;
        ///		&lt;td&gt;
        ///&lt;div class=&quot;detName&quot;&gt;			&lt;a href=&quot;/torrent/15314146/Stranger.Things.S01E05.720p.WEBRip.x264-SKGTV[ettv]&quot; class=&quot;detLink&quot; title=&quot;Details for Stranger.Things.S01E05.720p.WEBRip.x264-SKGTV[ettv]&quot;&gt;Stranger.Things.S01E05.720p.WEBRip.x264-SKGTV[ettv]&lt;/a&gt;
        ///&lt;/div&gt;
        ///&lt;a href=&quot;magnet:?xt=urn:btih:c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TorrentRowTrustedUploader {
            get {
                return ResourceManager.GetString("TorrentRowTrustedUploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///  &lt;td class=&quot;vertTh&quot;&gt;
        ///    &lt;center&gt;
        ///	  &lt;a href=&quot;/browse/200&quot; title=&quot;More from this category&quot;&gt;Video&lt;/a&gt;
        ///	  &lt;br&gt;
        ///	  (&lt;a href=&quot;/browse/208&quot; title=&quot;More from this category&quot;&gt;HD - TV shows&lt;/a&gt;)
        ///	&lt;/center&gt;
        ///  &lt;/td&gt;
        ///  &lt;td&gt;
        ///    &lt;div class=&quot;detName&quot;&gt;
        ///      &lt;a href=&quot;/torrent/12678054/Rick_and_Morty_Season_2_[WEBRIP]_[1080p]_[HEVC]&quot; class=&quot;detLink&quot; title=&quot;Details for Rick and Morty Season 2 [WEBRIP] [1080p] [HEVC]&quot;&gt;
        ///	    Rick and Morty Season 2 [WEBRIP] [1080p] [HEVC]
        ///	  &lt;/a&gt;
        ///    &lt;/div&gt;
        ///    &lt;a href=&quot;ma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TorrentRowVipUploader {
            get {
                return ResourceManager.GetString("TorrentRowVipUploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///  &lt;td class=&quot;vertTh&quot;&gt;
        ///    &lt;center&gt;
        ///	  &lt;a href=&quot;/browse/200&quot; title=&quot;More from this category&quot;&gt;Video&lt;/a&gt;
        ///	  &lt;br&gt;
        ///	  (&lt;a href=&quot;/browse/208&quot; title=&quot;More from this category&quot;&gt;HD - TV shows&lt;/a&gt;)
        ///	&lt;/center&gt;
        ///  &lt;/td&gt;
        ///  &lt;td&gt;
        ///    &lt;div class=&quot;detName&quot;&gt;
        ///      &lt;a href=&quot;/torrent/12678054/Rick_and_Morty_Season_2_[WEBRIP]_[1080p]_[HEVC]&quot; class=&quot;detLink&quot; title=&quot;Details for Rick and Morty Season 2 [WEBRIP] [1080p] [HEVC]&quot;&gt;		      		Rick and Morty Season 2 [WEBRIP] [1080p] [HEVC]     	  &lt;/a&gt;
        ///    &lt;/div&gt;
        ///    &lt;a hr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TorrentRowWhiteSpaceAroundTitle {
            get {
                return ResourceManager.GetString("TorrentRowWhiteSpaceAroundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr class=&quot;alt&quot;&gt;
        ///		&lt;td class=&quot;vertTh&quot;&gt;
        ///			&lt;center&gt;
        ///				&lt;a href=&quot;/browse/200&quot; title=&quot;More from this category&quot;&gt;Video&lt;/a&gt;&lt;br&gt;
        ///				(&lt;a href=&quot;/browse/205&quot; title=&quot;More from this category&quot;&gt;TV shows&lt;/a&gt;)
        ///			&lt;/center&gt;
        ///		&lt;/td&gt;
        ///		&lt;td&gt;
        ///&lt;div class=&quot;detName&quot;&gt;			&lt;a href=&quot;/torrent/16216005/Occultic.Nine.S01E05.720p.HEVC.x265-MeGusta&quot; class=&quot;detLink&quot; title=&quot;Details for Occultic.Nine.S01E05.720p.HEVC.x265-MeGusta&quot;&gt;Occultic.Nine.S01E05.720p.HEVC.x265-MeGusta&lt;/a&gt;
        ///&lt;/div&gt;
        ///&lt;a href=&quot;magnet:?xt=urn:btih:cd73cdc6abbd19a9e3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TorrentRowYdayPublish {
            get {
                return ResourceManager.GetString("TorrentRowYdayPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;rss version=&quot;1.0&quot; xmlns:torznab=&quot;http://torznab.com/schemas/2015/feed&quot;&gt;
        ///&lt;channel&gt;
        ///&lt;title&gt;PirateAPI&lt;/title&gt;
        ///&lt;description&gt;PirateBay Torznab API&lt;/description&gt;
        ///&lt;link&gt;https://github.com/Thosedarnmonkeys/PirateAPI&lt;/link&gt;
        ///&lt;item&gt;
        ///&lt;title&gt;Show Name S01E01 SD&lt;/title&gt;
        ///&lt;torznab:attr name=&quot;magneturl&quot; value=&quot;fakeUrl&quot; /&gt;
        ///&lt;pubDate&gt;Wed, 07 Sep 2016 00:00:00 +0000&lt;/pubDate&gt;
        ///&lt;size&gt;1024&lt;/size&gt;
        ///&lt;enclosure url=&quot;fakeUrl&quot; length=&quot;1024&quot; type=&quot;application/x-bittorrent&quot; /&gt;
        ///&lt;torznab: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TorznabResponse5Items {
            get {
                return ResourceManager.GetString("TorznabResponse5Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;rss version=&quot;1.0&quot; xmlns:torznab=&quot;http://torznab.com/schemas/2015/feed&quot;&gt;
        ///&lt;channel&gt;
        ///&lt;title&gt;PirateAPI&lt;/title&gt;
        ///&lt;description&gt;PirateBay Torznab API&lt;/description&gt;
        ///&lt;link&gt;https://github.com/Thosedarnmonkeys/PirateAPI&lt;/link&gt;
        ///&lt;item&gt;
        ///&lt;title&gt;Rick and Morty Season 2 [WEBRIP] [1080p] [HEVC]&lt;/title&gt;
        ///&lt;torznab:attr name=&quot;magneturl&quot; value=&quot;magnet:?xt=urn:btih:0494a80532b5b05dde567c61220d93406b7e22e7&amp;amp;dn=Rick+and+Morty+Season+2+%5BWEBRIP%5D+%5B1080p%5D+%5BHEVC%5D&amp;amp;tr=udp%3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TorznabResponseNoMagnets {
            get {
                return ResourceManager.GetString("TorznabResponseNoMagnets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;rss version=&quot;1.0&quot; xmlns:torznab=&quot;http://torznab.com/schemas/2015/feed&quot;&gt;
        ///&lt;channel&gt;
        ///&lt;title&gt;PirateAPI&lt;/title&gt;
        ///&lt;description&gt;PirateBay Torznab API&lt;/description&gt;
        ///&lt;link&gt;https://github.com/Thosedarnmonkeys/PirateAPI&lt;/link&gt;
        ///&lt;item&gt;
        ///&lt;title&gt;Rick.and.Morty.S02E01.HDTV.x264-BATV[ettv]&lt;/title&gt;
        ///&lt;torznab:attr name=&quot;magneturl&quot; value=&quot;magnet:?xt=urn:btih:f9e844d430fd38e36ece24938c3d613f875af3eb&amp;amp;dn=Rick.and.Morty.S02E01.HDTV.x264-BATV%5Bettv%5D&amp;amp;tr=udp%3A%2F%2Ftracker.lee [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TorznabResponseSingleEpisode {
            get {
                return ResourceManager.GetString("TorznabResponseSingleEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;rss version=&quot;1.0&quot; xmlns:torznab=&quot;http://torznab.com/schemas/2015/feed&quot;&gt;
        ///&lt;channel&gt;
        ///&lt;title&gt;PirateAPI&lt;/title&gt;
        ///&lt;description&gt;PirateBay Torznab API&lt;/description&gt;
        ///&lt;link&gt;https://github.com/Thosedarnmonkeys/PirateAPI&lt;/link&gt;
        ///&lt;item&gt;
        ///&lt;title&gt;Show Name S01E01 SD&lt;/title&gt;
        ///&lt;torznab:attr name=&quot;magneturl&quot; value=&quot;fakeUrl&quot; /&gt;
        ///&lt;pubDate&gt;Wed, 07 Sep 2016 00:00:00 +0000&lt;/pubDate&gt;
        ///&lt;size&gt;1024&lt;/size&gt;
        ///&lt;enclosure url=&quot;fakeUrl&quot; length=&quot;1024&quot; type=&quot;application/x-bittorrent&quot; /&gt;
        ///&lt;torznab: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TorznabResponseSingleItem {
            get {
                return ResourceManager.GetString("TorznabResponseSingleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;rss version=&quot;1.0&quot; xmlns:torznab=&quot;http://torznab.com/schemas/2015/feed&quot;&gt;
        ///&lt;channel&gt;
        ///&lt;title&gt;PirateAPI&lt;/title&gt;
        ///&lt;description&gt;PirateBay Torznab API&lt;/description&gt;
        ///&lt;link&gt;https://github.com/Thosedarnmonkeys/PirateAPI&lt;/link&gt;
        ///&lt;item&gt;
        ///&lt;title&gt;Rick and Morty Season 2 [WEBRIP] [1080p] [HEVC]&lt;/title&gt;
        ///&lt;torznab:attr name=&quot;magneturl&quot; value=&quot;magnet:?xt=urn:btih:0494a80532b5b05dde567c61220d93406b7e22e7&amp;amp;dn=Rick+and+Morty+Season+2+%5BWEBRIP%5D+%5B1080p%5D+%5BHEVC%5D&amp;amp;tr=udp%3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TorznabResponseSingleSeason {
            get {
                return ResourceManager.GetString("TorznabResponseSingleSeason", resourceCulture);
            }
        }
    }
}
